### ISSUE TITLE
Chrome crashes on macOS Tahoe (26.1) - request for bundled Chromium option

### ISSUE THREAD

**Issue by bobbybeers** [PleasePrompto/notebooklm-mcp#13]
## Summary

Chrome 143 crashes immediately with SIGSEGV when launched via the MCP on macOS Tahoe (26.1 beta). The crash occurs during browser initialization before any auth flow can begin.

## Environment

- **macOS**: 26.1 (25B78) - Tahoe beta
- **Chrome**: 143.0.7499.170
- **Hardware**: Mac16,8 (MacBook Pro M4 Pro)
- **Node**: v20.18.3
- **notebooklm-mcp**: latest via npx

## Crash Details

```
Exception Type:    EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000000000004a0
Termination Reason: Namespace SIGNAL, Code 11, Segmentation fault: 11

Thread 0 Crashed:: CrBrowserMain
0   Google Chrome Framework    ChromeMain + 60464420
...
Parent Process: node [16399]
```

The crash happens in Chrome's main thread during initialization, specifically when Playwright/patchright launches Chrome with the DevTools protocol connection.

## Root Cause

The MCP hardcodes `channel: "chrome"` in `src/session/shared-context-manager.ts`:

```typescript
const launchOptions = {
  // ...
  channel: "chrome" as const,
  // ...
};
```

This forces the use of system Chrome rather than Playwright's bundled Chromium. System Chrome 143 appears to have compatibility issues with macOS Tahoe when launched via automation.

## Proposed Solution

Add an environment variable to optionally skip the `channel: "chrome"` setting and use Playwright's bundled Chromium instead:

```typescript
const launchOptions = {
  // ...
  ...(process.env.NOTEBOOK_USE_BUNDLED_CHROMIUM !== 'true' && { channel: "chrome" as const }),
  // ...
};
```

Or similar configuration option.

## Workaround Attempted

I installed Playwright's bundled Chromium (`npx playwright install chromium`) and set `PLAYWRIGHT_BROWSERS_PATH` but this doesn't help because the MCP explicitly requests system Chrome via the channel option.

## Additional Context

- Playwright's bundled Chromium (143.0.7499.4) is available at `~/Library/Caches/ms-playwright/chromium-1200`
- The crash is 100% reproducible on every `setup_auth` attempt
- macOS Tahoe is in beta, so this may affect early adopters

Thanks for the great tool! Happy to provide additional crash logs or test patches if helpful.

**Comment by PleasePrompto** [comment]
Fixed in v2.0.0 — automatic Chromium fallback. When system Chrome can't launch (incl. macOS Tahoe crashes), we retry with the bundled Patchright Chromium. Force it from the start via `BROWSER_CHANNEL=chromium`. Thanks!

**Comment by S-Claw** [comment]
Corroborating data point from a different NotebookLM automation (own Playwright driver, not this MCP, but same pattern: `channel: "chrome"` + `launchPersistentContext` headless):

Branded Google Chrome crashes on macOS 26 are still happening well past the beta — now on **Chrome 152.0.7977.64 stable / macOS 26.5.2 (25F84), Apple Silicon (M4)**.

Crash signature (from `~/Library/Logs/DiagnosticReports/Google Chrome-*.ips`):
- Thread: `CrBrowserMain` (browser main process, not a renderer)
- Mostly `EXC_BAD_ACCESS (SIGSEGV)`, occasionally `EXC_BREAKPOINT (SIGTRAP)`
- Identical top-frame offsets across 6 crashes in 3 days → single crash site
- In our case it fires during the **PDF export/download stage** (`download.saveAs` → "Target page, context or browser has been closed"), not at launch — generation itself completes fine. 6 out of 7 download attempts crashed over 3 days.

Two side effects worth knowing for anyone automating NotebookLM with persistent profiles:
1. The crash leaves a stale `SingletonLock` pointing at a dead PID, so the *next* launch fails with `ProcessSingleton` errors until you clean `Singleton{Lock,Cookie,Socket}` from the profile dir.
2. Retrying with a fresh launch that only re-downloads (reusing the already-generated notebook) works — the crash window seems specific to the long-lived session.

So +1 for a bundled-Chromium option: branded-Chrome-only automation on macOS 26 is currently fragile at a Chrome-bug level that projects like this can't fix themselves.

**Comment by S-Claw** [comment]
Follow-up to my earlier comment: **Chrome 152.0.7977.65 stable does NOT fix this.**

Chrome auto-updated .64 → .65 on our machine this morning (macOS 26.5.2, Apple Silicon M4); the very next automation run crashed twice at the same PDF export/download stage — both the initial attempt and a fresh-launch retry.

From the two new `.ips` reports (`app_version: 152.0.7977.65`):
- `EXC_BAD_ACCESS (SIGSEGV)` on `CrBrowserMain`, both crashes
- Identical top-frame offsets across both .65 crashes → still a single crash site
- Same behavioral signature as .64: generation completes fine, crash fires during `download.saveAs` (Playwright reports "Target page, context or browser has been closed")

The crash remains probabilistic rather than deterministic — a subsequent re-download attempt on .65 went through cleanly. So the mitigation pattern from my previous comment (clean `Singleton*` from the profile dir, then retry download-only against the already-generated notebook) still works, and still seems necessary.

Net: anyone pinning hopes on the next stable to unbreak branded-Chrome automation on macOS 26 — .65 is not it.
